#!/bin/python3

# Complete the time_delta function below.
def time_delta(t1, t2):
    #Sun 10 May 2015 13:54:36 -0700
    import datetime
    time_format = "%a %d %b %Y %H:%M:%S %z"
    t1 = datetime.datetime.strptime(t1, time_format)
    t2 = datetime.datetime.strptime(t2, time_format)
    delta = (t1-t2).total_seconds()
    return str(int(abs(delta)))

print(time_delta("Sat 02 May 2015 19:54:36 +0530","Fri 01 May 2015 13:54:36 -0000"))

